export const elements = [
    {
        number: 1,
        symbol: 'H',
        name: 'Hydrogen',
        mass: 1.008,
        category: 'nonmetal',
        period: 1,
        group: 1,
        block: 's',
        electronConfig: '1s¹',
        electronegativity: 2.20
    },
    {
        number: 2,
        symbol: 'He',
        name: 'Helium',
        mass: 4.003,
        category: 'noble-gas',
        period: 1,
        group: 18,
        block: 's',
        electronConfig: '1s²',
        electronegativity: null
    },
    {
        number: 3,
        symbol: 'Li',
        name: 'Lithium',
        mass: 6.941,
        category: 'alkali-metal',
        period: 2,
        group: 1,
        block: 's',
        electronConfig: '[He]2s¹',
        electronegativity: 0.98
    },
    {
        number: 4,
        symbol: 'Be',
        name: 'Beryllium',
        mass: 9.012,
        category: 'alkaline-earth',
        period: 2,
        group: 2,
        block: 's',
        electronConfig: '[He]2s²',
        electronegativity: 1.57
    },
    {
        number: 5,
        symbol: 'B',
        name: 'Boron',
        mass: 10.811,
        category: 'metalloid',
        period: 2,
        group: 13,
        block: 'p',
        electronConfig: '[He]2s²2p¹',
        electronegativity: 2.04
    },
    {
        number: 6,
        symbol: 'C',
        name: 'Carbon',
        mass: 12.011,
        category: 'nonmetal',
        period: 2,
        group: 14,
        block: 'p',
        electronConfig: '[He]2s²2p²',
        electronegativity: 2.55
    },
    {
        number: 7,
        symbol: 'N',
        name: 'Nitrogen',
        mass: 14.007,
        category: 'nonmetal',
        period: 2,
        group: 15,
        block: 'p',
        electronConfig: '[He]2s²2p³',
        electronegativity: 3.04
    },
    {
        number: 8,
        symbol: 'O',
        name: 'Oxygen',
        mass: 15.999,
        category: 'nonmetal',
        period: 2,
        group: 16,
        block: 'p',
        electronConfig: '[He]2s²2p⁴',
        electronegativity: 3.44
    },
    {
        number: 9,
        symbol: 'F',
        name: 'Fluorine',
        mass: 18.998,
        category: 'nonmetal',
        period: 2,
        group: 17,
        block: 'p',
        electronConfig: '[He]2s²2p⁵',
        electronegativity: 3.98
    },
    {
        number: 10,
        symbol: 'Ne',
        name: 'Neon',
        mass: 20.180,
        category: 'noble-gas',
        period: 2,
        group: 18,
        block: 'p',
        electronConfig: '[He]2s²2p⁶',
        electronegativity: null
    },
    {
        number: 11,
        symbol: 'Na',
        name: 'Sodium',
        mass: 22.990,
        category: 'alkali-metal',
        period: 3,
        group: 1,
        block: 's',
        electronConfig: '[Ne]3s¹',
        electronegativity: 0.93
    },
    {
        number: 12,
        symbol: 'Mg',
        name: 'Magnesium',
        mass: 24.305,
        category: 'alkaline-earth',
        period: 3,
        group: 2,
        block: 's',
        electronConfig: '[Ne]3s²',
        electronegativity: 1.31
    },
    {
        number: 13,
        symbol: 'Al',
        name: 'Aluminum',
        mass: 26.982,
        category: 'post-transition',
        period: 3,
        group: 13,
        block: 'p',
        electronConfig: '[Ne]3s²3p¹',
        electronegativity: 1.61
    },
    {
        number: 14,
        symbol: 'Si',
        name: 'Silicon',
        mass: 28.086,
        category: 'metalloid',
        period: 3,
        group: 14,
        block: 'p',
        electronConfig: '[Ne]3s²3p²',
        electronegativity: 1.90
    },
    {
        number: 15,
        symbol: 'P',
        name: 'Phosphorus',
        mass: 30.974,
        category: 'nonmetal',
        period: 3,
        group: 15,
        block: 'p',
        electronConfig: '[Ne]3s²3p³',
        electronegativity: 2.19
    },
    {
        number: 16,
        symbol: 'S',
        name: 'Sulfur',
        mass: 32.065,
        category: 'nonmetal',
        period: 3,
        group: 16,
        block: 'p',
        electronConfig: '[Ne]3s²3p⁴',
        electronegativity: 2.58
    },
    {
        number: 17,
        symbol: 'Cl',
        name: 'Chlorine',
        mass: 35.453,
        category: 'nonmetal',
        period: 3,
        group: 17,
        block: 'p',
        electronConfig: '[Ne]3s²3p⁵',
        electronegativity: 3.16
    },
    {
        number: 18,
        symbol: 'Ar',
        name: 'Argon',
        mass: 39.948,
        category: 'noble-gas',
        period: 3,
        group: 18,
        block: 'p',
        electronConfig: '[Ne]3s²3p⁶',
        electronegativity: null
    },
    {
        number: 19,
        symbol: 'K',
        name: 'Potassium',
        mass: 39.098,
        category: 'alkali-metal',
        period: 4,
        group: 1,
        block: 's',
        electronConfig: '[Ar]4s¹',
        electronegativity: 0.82
    },
    {
        number: 20,
        symbol: 'Ca',
        name: 'Calcium',
        mass: 40.078,
        category: 'alkaline-earth',
        period: 4,
        group: 2,
        block: 's',
        electronConfig: '[Ar]4s²',
        electronegativity: 1.00
    },
    {
        number: 21,
        symbol: 'Sc',
        name: 'Scandium',
        mass: 44.956,
        category: 'transition-metal',
        period: 4,
        group: 3,
        block: 'd',
        electronConfig: '[Ar]3d¹4s²',
        electronegativity: 1.36
    },
    {
        number: 22,
        symbol: 'Ti',
        name: 'Titanium',
        mass: 47.867,
        category: 'transition-metal',
        period: 4,
        group: 4,
        block: 'd',
        electronConfig: '[Ar]3d²4s²',
        electronegativity: 1.54
    },
    {
        number: 23,
        symbol: 'V',
        name: 'Vanadium',
        mass: 50.942,
        category: 'transition-metal',
        period: 4,
        group: 5,
        block: 'd',
        electronConfig: '[Ar]3d³4s²',
        electronegativity: 1.63
    },
    {
        number: 24,
        symbol: 'Cr',
        name: 'Chromium',
        mass: 51.996,
        category: 'transition-metal',
        period: 4,
        group: 6,
        block: 'd',
        electronConfig: '[Ar]3d⁵4s¹',
        electronegativity: 1.66
    },
    {
        number: 25,
        symbol: 'Mn',
        name: 'Manganese',
        mass: 54.938,
        category: 'transition-metal',
        period: 4,
        group: 7,
        block: 'd',
        electronConfig: '[Ar]3d⁵4s²',
        electronegativity: 1.55
    },
    {
        number: 26,
        symbol: 'Fe',
        name: 'Iron',
        mass: 55.845,
        category: 'transition-metal',
        period: 4,
        group: 8,
        block: 'd',
        electronConfig: '[Ar]3d⁶4s²',
        electronegativity: 1.83
    },
    {
        number: 27,
        symbol: 'Co',
        name: 'Cobalt',
        mass: 58.933,
        category: 'transition-metal',
        period: 4,
        group: 9,
        block: 'd',
        electronConfig: '[Ar]3d⁷4s²',
        electronegativity: 1.88
    },
    {
        number: 28,
        symbol: 'Ni',
        name: 'Nickel',
        mass: 58.693,
        category: 'transition-metal',
        period: 4,
        group: 10,
        block: 'd',
        electronConfig: '[Ar]3d⁸4s²',
        electronegativity: 1.91
    },
    {
        number: 29,
        symbol: 'Cu',
        name: 'Copper',
        mass: 63.546,
        category: 'transition-metal',
        period: 4,
        group: 11,
        block: 'd',
        electronConfig: '[Ar]3d¹⁰4s¹',
        electronegativity: 1.90
    },
    {
        number: 30,
        symbol: 'Zn',
        name: 'Zinc',
        mass: 65.38,
        category: 'transition-metal',
        period: 4,
        group: 12,
        block: 'd',
        electronConfig: '[Ar]3d¹⁰4s²',
        electronegativity: 1.65
    },
    {
        number: 31,
        symbol: 'Ga',
        name: 'Gallium',
        mass: 69.723,
        category: 'post-transition',
        period: 4,
        group: 13,
        block: 'p',
        electronConfig: '[Ar]3d¹⁰4s²4p¹',
        electronegativity: 1.81
    },
    {
        number: 32,
        symbol: 'Ge',
        name: 'Germanium',
        mass: 72.63,
        category: 'metalloid',
        period: 4,
        group: 14,
        block: 'p',
        electronConfig: '[Ar]3d¹⁰4s²4p²',
        electronegativity: 2.01
    },
    {
        number: 33,
        symbol: 'As',
        name: 'Arsenic',
        mass: 74.922,
        category: 'metalloid',
        period: 4,
        group: 15,
        block: 'p',
        electronConfig: '[Ar]3d¹⁰4s²4p³',
        electronegativity: 2.18
    },
    {
        number: 34,
        symbol: 'Se',
        name: 'Selenium',
        mass: 78.971,
        category: 'nonmetal',
        period: 4,
        group: 16,
        block: 'p',
        electronConfig: '[Ar]3d¹⁰4s²4p⁴',
        electronegativity: 2.55
    },
    {
        number: 35,
        symbol: 'Br',
        name: 'Bromine',
        mass: 79.904,
        category: 'nonmetal',
        period: 4,
        group: 17,
        block: 'p',
        electronConfig: '[Ar]3d¹⁰4s²4p⁵',
        electronegativity: 2.96
    },
    {
        number: 36,
        symbol: 'Kr',
        name: 'Krypton',
        mass: 83.798,
        category: 'noble-gas',
        period: 4,
        group: 18,
        block: 'p',
        electronConfig: '[Ar]3d¹⁰4s²4p⁶',
        electronegativity: null
    },
    {
        number: 37,
        symbol: 'Rb',
        name: 'Rubidium',
        mass: 85.468,
        category: 'alkali-metal',
        period: 5,
        group: 1,
        block: 's',
        electronConfig: '[Kr]5s¹',
        electronegativity: 0.82
    },
    {
        number: 38,
        symbol: 'Sr',
        name: 'Strontium',
        mass: 87.62,
        category: 'alkaline-earth',
        period: 5,
        group: 2,
        block: 's',
        electronConfig: '[Kr]5s²',
        electronegativity: 0.95
    },
    {
        number: 39,
        symbol: 'Y',
        name: 'Yttrium',
        mass: 88.906,
        category: 'transition-metal',
        period: 5,
        group: 3,
        block: 'd',
        electronConfig: '[Kr]4d¹5s²',
        electronegativity: 1.22
    },
    {
        number: 40,
        symbol: 'Zr',
        name: 'Zirconium',
        mass: 91.224,
        category: 'transition-metal',
        period: 5,
        group: 4,
        block: 'd',
        electronConfig: '[Kr]4d²5s²',
        electronegativity: 1.33
    },
    {
        number: 41,
        symbol: 'Nb',
        name: 'Niobium',
        mass: 92.906,
        category: 'transition-metal',
        period: 5,
        group: 5,
        block: 'd',
        electronConfig: '[Kr]4d⁴5s¹',
        electronegativity: 1.6
    },
    {
        number: 42,
        symbol: 'Mo',
        name: 'Molybdenum',
        mass: 95.95,
        category: 'transition-metal',
        period: 5,
        group: 6,
        block: 'd',
        electronConfig: '[Kr]4d⁵5s¹',
        electronegativity: 2.16
    },
    {
        number: 43,
        symbol: 'Tc',
        name: 'Technetium',
        mass: 98,
        category: 'transition-metal',
        period: 5,
        group: 7,
        block: 'd',
        electronConfig: '[Kr]4d⁵5s²',
        electronegativity: 1.9
    },
    {
        number: 44,
        symbol: 'Ru',
        name: 'Ruthenium',
        mass: 101.07,
        category: 'transition-metal',
        period: 5,
        group: 8,
        block: 'd',
        electronConfig: '[Kr]4d⁷5s¹',
        electronegativity: 2.2
    },
    {
        number: 45,
        symbol: 'Rh',
        name: 'Rhodium',
        mass: 102.91,
        category: 'transition-metal',
        period: 5,
        group: 9,
        block: 'd',
        electronConfig: '[Kr]4d⁸5s¹',
        electronegativity: 2.28
    },
    {
        number: 46,
        symbol: 'Pd',
        name: 'Palladium',
        mass: 106.42,
        category: 'transition-metal',
        period: 5,
        group: 10,
        block: 'd',
        electronConfig: '[Kr]4d¹⁰',
        electronegativity: 2.20
    },
    {
        number: 47,
        symbol: 'Ag',
        name: 'Silver',
        mass: 107.87,
        category: 'transition-metal',
        period: 5,
        group: 11,
        block: 'd',
        electronConfig: '[Kr]4d¹⁰5s¹',
        electronegativity: 1.93
    },
    {
        number: 48,
        symbol: 'Cd',
        name: 'Cadmium',
        mass: 112.41,
        category: 'transition-metal',
        period: 5,
        group: 12,
        block: 'd',
        electronConfig: '[Kr]4d¹⁰5s²',
        electronegativity: 1.69
    },
    {
        number: 49,
        symbol: 'In',
        name: 'Indium',
        mass: 114.82,
        category: 'post-transition',
        period: 5,
        group: 13,
        block: 'p',
        electronConfig: '[Kr]4d¹⁰5s²5p¹',
        electronegativity: 1.78
    },
    {
        number: 50,
        symbol: 'Sn',
        name: 'Tin',
        mass: 118.71,
        category: 'post-transition',
        period: 5,
        group: 14,
        block: 'p',
        electronConfig: '[Kr]4d¹⁰5s²5p²',
        electronegativity: 1.96
    },
    {
        number: 51,
        symbol: 'Sb',
        name: 'Antimony',
        mass: 121.76,
        category: 'metalloid',
        period: 5,
        group: 15,
        block: 'p',
        electronConfig: '[Kr]4d¹⁰5s²5p³',
        electronegativity: 2.05
    },
    {
        number: 52,
        symbol: 'Te',
        name: 'Tellurium',
        mass: 127.60,
        category: 'metalloid',
        period: 5,
        group: 16,
        block: 'p',
        electronConfig: '[Kr]4d¹⁰5s²5p⁴',
        electronegativity: 2.1
    },
    {
        number: 53,
        symbol: 'I',
        name: 'Iodine',
        mass: 126.90,
        category: 'nonmetal',
        period: 5,
        group: 17,
        block: 'p',
        electronConfig: '[Kr]4d¹⁰5s²5p⁵',
        electronegativity: 2.66
    },
    {
        number: 54,
        symbol: 'Xe',
        name: 'Xenon',
        mass: 131.29,
        category: 'noble-gas',
        period: 5,
        group: 18,
        block: 'p',
        electronConfig: '[Kr]4d¹⁰5s²5p⁶',
        electronegativity: null
    },
    {
        number: 55,
        symbol: 'Cs',
        name: 'Cesium',
        mass: 132.91,
        category: 'alkali-metal',
        period: 6,
        group: 1,
        block: 's',
        electronConfig: '[Xe]6s¹',
        electronegativity: 0.79
    },
    {
        number: 56,
        symbol: 'Ba',
        name: 'Barium',
        mass: 137.33,
        category: 'alkaline-earth',
        period: 6,
        group: 2,
        block: 's',
        electronConfig: '[Xe]6s²',
        electronegativity: 0.89
    },
    {
        number: 57,
        symbol: 'La',
        name: 'Lanthanum',
        mass: 138.91,
        category: 'lanthanide',
        period: 6,
        group: 3,
        block: 'f',
        electronConfig: '[Xe]5d¹6s²',
        electronegativity: 1.10
    },
    {
        number: 58,
        symbol: 'Ce',
        name: 'Cerium',
        mass: 140.12,
        category: 'lanthanide',
        period: 6,
        group: 3,
        block: 'f',
        electronConfig: '[Xe]4f¹5d¹6s²',
        electronegativity: 1.12
    },
    {
        number: 59,
        symbol: 'Pr',
        name: 'Praseodymium',
        mass: 140.91,
        category: 'lanthanide',
        period: 6,
        group: 3,
        block: 'f',
        electronConfig: '[Xe]4f³6s²',
        electronegativity: 1.13
    },
    {
        number: 60,
        symbol: 'Nd',
        name: 'Neodymium',
        mass: 144.24,
        category: 'lanthanide',
        period: 6,
        group: 3,
        block: 'f',
        electronConfig: '[Xe]4f⁴6s²',
        electronegativity: 1.14
    },
    {
        number: 61,
        symbol: 'Pm',
        name: 'Promethium',
        mass: 145,
        category: 'lanthanide',
        period: 6,
        group: 3,
        block: 'f',
        electronConfig: '[Xe]4f⁵6s²',
        electronegativity: 1.13
    },
    {
        number: 62,
        symbol: 'Sm',
        name: 'Samarium',
        mass: 150.36,
        category: 'lanthanide',
        period: 6,
        group: 3,
        block: 'f',
        electronConfig: '[Xe]4f⁶6s²',
        electronegativity: 1.17
    },
    {
        number: 63,
        symbol: 'Eu',
        name: 'Europium',
        mass: 151.96,
        category: 'lanthanide',
        period: 6,
        group: 3,
        block: 'f',
        electronConfig: '[Xe]4f⁷6s²',
        electronegativity: 1.2
    },
    {
        number: 64,
        symbol: 'Gd',
        name: 'Gadolinium',
        mass: 157.25,
        category: 'lanthanide',
        period: 6,
        group: 3,
        block: 'f',
        electronConfig: '[Xe]4f⁷5d¹6s²',
        electronegativity: 1.20
    },
    {
        number: 65,
        symbol: 'Tb',
        name: 'Terbium',
        mass: 158.93,
        category: 'lanthanide',
        period: 6,
        group: 3,
        block: 'f',
        electronConfig: '[Xe]4f⁹6s²',
        electronegativity: 1.2
    },
    {
        number: 66,
        symbol: 'Dy',
        name: 'Dysprosium',
        mass: 162.50,
        category: 'lanthanide',
        period: 6,
        group: 3,
        block: 'f',
        electronConfig: '[Xe]4f¹⁰6s²',
        electronegativity: 1.22
    },
    {
        number: 67,
        symbol: 'Ho',
        name: 'Holmium',
        mass: 164.93,
        category: 'lanthanide',
        period: 6,
        group: 3,
        block: 'f',
        electronConfig: '[Xe]4f¹¹6s²',
        electronegativity: 1.23
    },
    {
        number: 68,
        symbol: 'Er',
        name: 'Erbium',
        mass: 167.26,
        category: 'lanthanide',
        period: 6,
        group: 3,
        block: 'f',
        electronConfig: '[Xe]4f¹²6s²',
        electronegativity: 1.24
    },
    {
        number: 69,
        symbol: 'Tm',
        name: 'Thulium',
        mass: 168.93,
        category: 'lanthanide',
        period: 6,
        group: 3,
        block: 'f',
        electronConfig: '[Xe]4f¹³6s²',
        electronegativity: 1.25
    },
    {
        number: 70,
        symbol: 'Yb',
        name: 'Ytterbium',
        mass: 173.05,
        category: 'lanthanide',
        period: 6,
        group: 3,
        block: 'f',
        electronConfig: '[Xe]4f¹⁴6s²',
        electronegativity: 1.1
    },
    {
        number: 71,
        symbol: 'Lu',
        name: 'Lutetium',
        mass: 174.97,
        category: 'lanthanide',
        period: 6,
        group: 3,
        block: 'd',
        electronConfig: '[Xe]4f¹⁴5d¹6s²',
        electronegativity: 1.27
    },
    {
        number: 72,
        symbol: 'Hf',
        name: 'Hafnium',
        mass: 178.49,
        category: 'transition-metal',
        period: 6,
        group: 4,
        block: 'd',
        electronConfig: '[Xe]4f¹⁴5d²6s²',
        electronegativity: 1.3
    },
    {
        number: 73,
        symbol: 'Ta',
        name: 'Tantalum',
        mass: 180.95,
        category: 'transition-metal',
        period: 6,
        group: 5,
        block: 'd',
        electronConfig: '[Xe]4f¹⁴5d³6s²',
        electronegativity: 1.5
    },
    {
        number: 74,
        symbol: 'W',
        name: 'Tungsten',
        mass: 183.84,
        category: 'transition-metal',
        period: 6,
        group: 6,
        block: 'd',
        electronConfig: '[Xe]4f¹⁴5d⁴6s²',
        electronegativity: 2.36
    },
    {
        number: 75,
        symbol: 'Re',
        name: 'Rhenium',
        mass: 186.21,
        category: 'transition-metal',
        period: 6,
        group: 7,
        block: 'd',
        electronConfig: '[Xe]4f¹⁴5d⁵6s²',
        electronegativity: 1.9
    },
    {
        number: 76,
        symbol: 'Os',
        name: 'Osmium',
        mass: 190.23,
        category: 'transition-metal',
        period: 6,
        group: 8,
        block: 'd',
        electronConfig: '[Xe]4f¹⁴5d⁶6s²',
        electronegativity: 2.2
    },
    {
        number: 77,
        symbol: 'Ir',
        name: 'Iridium',
        mass: 192.22,
        category: 'transition-metal',
        period: 6,
        group: 9,
        block: 'd',
        electronConfig: '[Xe]4f¹⁴5d⁷6s²',
        electronegativity: 2.20
    },
    {
        number: 78,
        symbol: 'Pt',
        name: 'Platinum',
        mass: 195.08,
        category: 'transition-metal',
        period: 6,
        group: 10,
        block: 'd',
        electronConfig: '[Xe]4f¹⁴5d⁹6s¹',
        electronegativity: 2.28
    },
    {
        number: 79,
        symbol: 'Au',
        name: 'Gold',
        mass: 196.97,
        category: 'transition-metal',
        period: 6,
        group: 11,
        block: 'd',
        electronConfig: '[Xe]4f¹⁴5d¹⁰6s¹',
        electronegativity: 2.54
    },
    {
        number: 80,
        symbol: 'Hg',
        name: 'Mercury',
        mass: 200.59,
        category: 'transition-metal',
        period: 6,
        group: 12,
        block: 'd',
        electronConfig: '[Xe]4f¹⁴5d¹⁰6s²',
        electronegativity: 2.00
    },
    {
        number: 81,
        symbol: 'Tl',
        name: 'Thallium',
        mass: 204.38,
        category: 'post-transition',
        period: 6,
        group: 13,
        block: 'p',
        electronConfig: '[Xe]4f¹⁴5d¹⁰6s²6p¹',
        electronegativity: 1.62
    },
    {
        number: 82,
        symbol: 'Pb',
        name: 'Lead',
        mass: 207.2,
        category: 'post-transition',
        period: 6,
        group: 14,
        block: 'p',
        electronConfig: '[Xe]4f¹⁴5d¹⁰6s²6p²',
        electronegativity: 2.33
    },
    {
        number: 83,
        symbol: 'Bi',
        name: 'Bismuth',
        mass: 208.98,
        category: 'post-transition',
        period: 6,
        group: 15,
        block: 'p',
        electronConfig: '[Xe]4f¹⁴5d¹⁰6s²6p³',
        electronegativity: 2.02
    },
    {
        number: 84,
        symbol: 'Po',
        name: 'Polonium',
        mass: 209,
        category: 'post-transition',
        period: 6,
        group: 16,
        block: 'p',
        electronConfig: '[Xe]4f¹⁴5d¹⁰6s²6p⁴',
        electronegativity: 2.0
    },
    {
        number: 85,
        symbol: 'At',
        name: 'Astatine',
        mass: 210,
        category: 'metalloid',
        period: 6,
        group: 17,
        block: 'p',
        electronConfig: '[Xe]4f¹⁴5d¹⁰6s²6p⁵',
        electronegativity: 2.2
    },
    {
        number: 86,
        symbol: 'Rn',
        name: 'Radon',
        mass: 222,
        category: 'noble-gas',
        period: 6,
        group: 18,
        block: 'p',
        electronConfig: '[Xe]4f¹⁴5d¹⁰6s²6p⁶',
        electronegativity: null
    },
    {
        number: 87,
        symbol: 'Fr',
        name: 'Francium',
        mass: 223,
        category: 'alkali-metal',
        period: 7,
        group: 1,
        block: 's',
        electronConfig: '[Rn]7s¹',
        electronegativity: 0.7
    },
    {
        number: 88,
        symbol: 'Ra',
        name: 'Radium',
        mass: 226,
        category: 'alkaline-earth',
        period: 7,
        group: 2,
        block: 's',
        electronConfig: '[Rn]7s²',
        electronegativity: 0.9
    },
    {
        number: 89,
        symbol: 'Ac',
        name: 'Actinium',
        mass: 227,
        category: 'actinide',
        period: 7,
        group: 3,
        block: 'f',
        electronConfig: '[Rn]6d¹7s²',
        electronegativity: 1.1
    },
    {
        number: 90,
        symbol: 'Th',
        name: 'Thorium',
        mass: 232.04,
        category: 'actinide',
        period: 7,
        group: 3,
        block: 'f',
        electronConfig: '[Rn]6d²7s²',
        electronegativity: 1.3
    },
    {
        number: 91,
        symbol: 'Pa',
        name: 'Protactinium',
        mass: 231.04,
        category: 'actinide',
        period: 7,
        group: 3,
        block: 'f',
        electronConfig: '[Rn]5f²6d¹7s²',
        electronegativity: 1.5
    },
    {
        number: 92,
        symbol: 'U',
        name: 'Uranium',
        mass: 238.03,
        category: 'actinide',
        period: 7,
        group: 3,
        block: 'f',
        electronConfig: '[Rn]5f³6d¹7s²',
        electronegativity: 1.38
    },
    {
        number: 93,
        symbol: 'Np',
        name: 'Neptunium',
        mass: 237,
        category: 'actinide',
        period: 7,
        group: 3,
        block: 'f',
        electronConfig: '[Rn]5f⁴6d¹7s²',
        electronegativity: 1.36
    },
    {
        number: 94,
        symbol: 'Pu',
        name: 'Plutonium',
        mass: 244,
        category: 'actinide',
        period: 7,
        group: 3,
        block: 'f',
        electronConfig: '[Rn]5f⁶7s²',
        electronegativity: 1.28
    },
    {
        number: 95,
        symbol: 'Am',
        name: 'Americium',
        mass: 243,
        category: 'actinide',
        period: 7,
        group: 3,
        block: 'f',
        electronConfig: '[Rn]5f⁷7s²',
        electronegativity: 1.3
    },
    {
        number: 96,
        symbol: 'Cm',
        name: 'Curium',
        mass: 247,
        category: 'actinide',
        period: 7,
        group: 3,
        block: 'f',
        electronConfig: '[Rn]5f⁷6d¹7s²',
        electronegativity: 1.3
    },
    {
        number: 97,
        symbol: 'Bk',
        name: 'Berkelium',
        mass: 247,
        category: 'actinide',
        period: 7,
        group: 3,
        block: 'f',
        electronConfig: '[Rn]5f⁹7s²',
        electronegativity: 1.3
    },
    {
        number: 98,
        symbol: 'Cf',
        name: 'Californium',
        mass: 251,
        category: 'actinide',
        period: 7,
        group: 3,
        block: 'f',
        electronConfig: '[Rn]5f¹⁰7s²',
        electronegativity: 1.3
    },
    {
        number: 99,
        symbol: 'Es',
        name: 'Einsteinium',
        mass: 252,
        category: 'actinide',
        period: 7,
        group: 3,
        block: 'f',
        electronConfig: '[Rn]5f¹¹7s²',
        electronegativity: 1.3
    },
    {
        number: 100,
        symbol: 'Fm',
        name: 'Fermium',
        mass: 257,
        category: 'actinide',
        period: 7,
        group: 3,
        block: 'f',
        electronConfig: '[Rn]5f¹²7s²',
        electronegativity: 1.3
    },
    {
        number: 101,
        symbol: 'Md',
        name: 'Mendelevium',
        mass: 258,
        category: 'actinide',
        period: 7,
        group: 3,
        block: 'f',
        electronConfig: '[Rn]5f¹³7s²',
        electronegativity: 1.3
    },
    {
        number: 102,
        symbol: 'No',
        name: 'Nobelium',
        mass: 259,
        category: 'actinide',
        period: 7,
        group: 3,
        block: 'f',
        electronConfig: '[Rn]5f¹⁴7s²',
        electronegativity: 1.3
    },
    {
        number: 103,
        symbol: 'Lr',
        name: 'Lawrencium',
        mass: 262,
        category: 'actinide',
        period: 7,
        group: 3,
        block: 'd',
        electronConfig: '[Rn]5f¹⁴7s²7p¹',
        electronegativity: 1.3
    },
    {
        number: 104,
        symbol: 'Rf',
        name: 'Rutherfordium',
        mass: 267,
        category: 'transition-metal',
        period: 7,
        group: 4,
        block: 'd',
        electronConfig: '[Rn]5f¹⁴6d²7s²',
        electronegativity: null
    },
    {
        number: 105,
        symbol: 'Db',
        name: 'Dubnium',
        mass: 268,
        category: 'transition-metal',
        period: 7,
        group: 5,
        block: 'd',
        electronConfig: '[Rn]5f¹⁴6d³7s²',
        electronegativity: null
    },
    {
        number: 106,
        symbol: 'Sg',
        name: 'Seaborgium',
        mass: 269,
        category: 'transition-metal',
        period: 7,
        group: 6,
        block: 'd',
        electronConfig: '[Rn]5f¹⁴6d⁴7s²',
        electronegativity: null
    },
    {
        number: 107,
        symbol: 'Bh',
        name: 'Bohrium',
        mass: 270,
        category: 'transition-metal',
        period: 7,
        group: 7,
        block: 'd',
        electronConfig: '[Rn]5f¹⁴6d⁵7s²',
        electronegativity: null
    },
    {
        number: 108,
        symbol: 'Hs',
        name: 'Hassium',
        mass: 269,
        category: 'transition-metal',
        period: 7,
        group: 8,
        block: 'd',
        electronConfig: '[Rn]5f¹⁴6d⁶7s²',
        electronegativity: null
    },
    {
        number: 109,
        symbol: 'Mt',
        name: 'Meitnerium',
        mass: 278,
        category: 'transition-metal',
        period: 7,
        group: 9,
        block: 'd',
        electronConfig: '[Rn]5f¹⁴6d⁷7s²',
        electronegativity: null
    },
    {
        number: 110,
        symbol: 'Ds',
        name: 'Darmstadtium',
        mass: 281,
        category: 'transition-metal',
        period: 7,
        group: 10,
        block: 'd',
        electronConfig: '[Rn]5f¹⁴6d⁸7s²',
        electronegativity: null
    },
    {
        number: 111,
        symbol: 'Rg',
        name: 'Roentgenium',
        mass: 282,
        category: 'transition-metal',
        period: 7,
        group: 11,
        block: 'd',
        electronConfig: '[Rn]5f¹⁴6d⁹7s²',
        electronegativity: null
    },
    {
        number: 112,
        symbol: 'Cn',
        name: 'Copernicium',
        mass: 285,
        category: 'transition-metal',
        period: 7,
        group: 12,
        block: 'd',
        electronConfig: '[Rn]5f¹⁴6d¹⁰7s²',
        electronegativity: null
    },
    {
        number: 113,
        symbol: 'Nh',
        name: 'Nihonium',
        mass: 286,
        category: 'post-transition',
        period: 7,
        group: 13,
        block: 'p',
        electronConfig: '[Rn]5f¹⁴6d¹⁰7s²7p¹',
        electronegativity: null
    },
    {
        number: 114,
        symbol: 'Fl',
        name: 'Flerovium',
        mass: 289,
        category: 'post-transition',
        period: 7,
        group: 14,
        block: 'p',
        electronConfig: '[Rn]5f¹⁴6d¹⁰7s²7p²',
        electronegativity: null
    },
    {
        number: 115,
        symbol: 'Mc',
        name: 'Moscovium',
        mass: 290,
        category: 'post-transition',
        period: 7,
        group: 15,
        block: 'p',
        electronConfig: '[Rn]5f¹⁴6d¹⁰7s²7p³',
        electronegativity: null
    },
    {
        number: 116,
        symbol: 'Lv',
        name: 'Livermorium',
        mass: 293,
        category: 'post-transition',
        period: 7,
        group: 16,
        block: 'p',
        electronConfig: '[Rn]5f¹⁴6d¹⁰7s²7p⁴',
        electronegativity: null
    },
    {
        number: 117,
        symbol: 'Ts',
        name: 'Tennessine',
        mass: 294,
        category: 'post-transition',
        period: 7,
        group: 17,
        block: 'p',
        electronConfig: '[Rn]5f¹⁴6d¹⁰7s²7p⁵',
        electronegativity: null
    },
    {
        number: 118,
        symbol: 'Og',
        name: 'Oganesson',
        mass: 294,
        category: 'noble-gas',
        period: 7,
        group: 18,
        block: 'p',
        electronConfig: '[Rn]5f¹⁴6d¹⁰7s²7p⁶',
        electronegativity: null
    }
]; 